sources:
- archive: tdnf-3.6.1.tar.gz
  archive_type: upstream
  archive_sha512sum: b3f3e2d897f7a38c76a71255943ce430d26e9bf8510388529c5147a0275946c1785a552df69fe2f44d81a259db15c27127819c9f86cbdd6e7cf6e5d86b48fe0f
  version: 3.6.1
  name: tdnf-3.6.1
  url: https://github.com/vmware/tdnf/archive/refs/tags/v3.6.1.tar.gz
  repo_url: https://github.com/vmware/tdnf.git
  commit_id: d79720b8ed3618eca0dfbcbb2429f6cb680b3fd1
  spdx:
    package:
      detailed_description: tdnf - tiny dandified yum
      home_page: https://github.com/vmware/tdnf
      license_concluded: GPL-2.0-only AND BSD-3-Clause AND LGPL-2.1-or-later AND LGPL-2.1-only
      license_declared: GPL-2.0-only AND BSD-3-Clause AND LGPL-2.1-or-later AND LGPL-2.1-only
      short_summary: tdnf - tiny dandified yum
      supplier: 'Organization: Broadcom, Inc.'
