sources:
- archive: openssl-3.0.16.tar.gz
  archive_type: upstream
  archive_sha512sum: 5eea2b0c60d870549fc2b8755f1220a57f870d95fbc8d5cc5abb9589f212d10945f355c3e88ff48540a7ee1c4db774b936023ca33d7c799ea82d91eef9c1c16d
  version: 3.0.16
  name: openssl-3.0.16
  url: https://github.com/openssl/openssl/releases/download/openssl-3.0.16/openssl-3.0.16.tar.gz
  repo_url: https://github.com/openssl/openssl
  commit_id: fa1e5dfb142bb1c26c3c38a10aafa7a095df52e5
  missing:
  - .github
  - gost-engine
  - .gitmodules
  - pyca-cryptography
  - 90-team.norelease.conf
  - mktar.sh
  - krb5
  - .gitignore
  - .gitattributes
  - corpora
  - dev
  spdx:
    package:
      detailed_description: 'The OpenSSL package contains management tools and libraries
        relating to cryptography. These are useful for providing cryptography functions
        to other packages, such as OpenSSH, email applications and web browsers (for
        accessing HTTPS sites). '
      home_page: http://www.openssl.org
      license_concluded: (OpenSSL OR BSD-2-Clause) AND (OpenSSL OR BSD-3-Clause OR
        GPL-1.0-or-later) AND (GPL-2.0-or-later OR LGPL-2.1-or-later OR MPL-1.1 OR
        BSD-3-Clause) AND (OpenSSL OR BSD-3-Clause) AND (GPL-1.0-or-later OR Artistic-1.0-Perl)
        AND (GPL-1.0-or-later OR Artistic-1.0) AND (Artistic-1.0-Perl OR GPL-1.0-or-later)
        AND (OpenSSL OR BSD-3-Clause OR GPL-1.0-or-later OR GPL-2.0-only) AND BSD-2-Clause
        AND BSD-3-Clause AND Apache-2.0 AND OpenSSL AND snprintf AND GPL-1.0-only
        AND Artistic-1.0 AND BSD-Source-Code AND CC0-1.0
      license_declared: (OpenSSL OR BSD-2-Clause) AND (OpenSSL OR BSD-3-Clause OR
        GPL-1.0-or-later) AND (GPL-2.0-or-later OR LGPL-2.1-or-later OR MPL-1.1 OR
        BSD-3-Clause) AND (OpenSSL OR BSD-3-Clause) AND (GPL-1.0-or-later OR Artistic-1.0-Perl)
        AND (GPL-1.0-or-later OR Artistic-1.0) AND (Artistic-1.0-Perl OR GPL-1.0-or-later)
        AND (OpenSSL OR BSD-3-Clause OR GPL-1.0-or-later OR GPL-2.0-only) AND BSD-2-Clause
        AND BSD-3-Clause AND Apache-2.0 AND OpenSSL AND snprintf AND GPL-1.0-only
        AND Artistic-1.0 AND BSD-Source-Code AND CC0-1.0
      short_summary: Management tools and libraries relating to cryptography
      supplier: 'Organization: Broadcom, Inc.'
- archive: openssl-3.1.2.tar.gz
  archive_type: upstream
  archive_sha512sum: c48ad86265b0fee18b23863b645a286d131a863a3418c7d2ed6c819eebb822ad0f2985ba3ecbf4def32515442f0eb40aba08f3146d113247e86ec80fbddca1c1
  version: 3.1.2
  name: openssl-openssl-3.1.2
  url: https://github.com/openssl/openssl/archive/refs/tags/openssl-3.1.2.tar.gz
  repo_url: https://github.com/openssl/openssl
  commit_id: 17a2c5111864d8e016c5f2d29c40a3746b559e9d
  missing:
  - .github
  - .gitattributes
  - .gitmodules
  - mktar.sh
  - gost-engine
  - corpora
  - krb5
  - pyca-cryptography
  - .gitignore
  - dev
  spdx:
    package:
      detailed_description: 'Fips library for enabling fips. '
      home_page: http://www.openssl.org
      license_concluded: (GPL-1.0-or-later OR Artistic-1.0) AND (OpenSSL OR BSD-3-Clause
        OR GPL-1.0-or-later OR GPL-2.0-only) AND (OpenSSL OR BSD-3-Clause) AND (GPL-1.0-or-later
        OR Artistic-1.0-Perl) AND (OpenSSL OR BSD-3-Clause OR GPL-1.0-or-later) AND
        (OpenSSL OR BSD-2-Clause) AND (GPL-2.0-or-later OR LGPL-2.1-or-later OR MPL-1.1
        OR BSD-3-Clause) AND (Artistic-1.0-Perl OR GPL-1.0-or-later) AND snprintf
        AND Apache-2.0 AND BSD-3-Clause AND GPL-1.0-only AND CC0-1.0 AND BSD-Source-Code
        AND Artistic-1.0 AND OpenSSL AND BSD-2-Clause
      license_declared: (GPL-1.0-or-later OR Artistic-1.0) AND (OpenSSL OR BSD-3-Clause
        OR GPL-1.0-or-later OR GPL-2.0-only) AND (OpenSSL OR BSD-3-Clause) AND (GPL-1.0-or-later
        OR Artistic-1.0-Perl) AND (OpenSSL OR BSD-3-Clause OR GPL-1.0-or-later) AND
        (OpenSSL OR BSD-2-Clause) AND (GPL-2.0-or-later OR LGPL-2.1-or-later OR MPL-1.1
        OR BSD-3-Clause) AND (Artistic-1.0-Perl OR GPL-1.0-or-later) AND snprintf
        AND Apache-2.0 AND BSD-3-Clause AND GPL-1.0-only AND CC0-1.0 AND BSD-Source-Code
        AND Artistic-1.0 AND OpenSSL AND BSD-2-Clause
      short_summary: FIPS Libraries for openssl
      supplier: 'Organization: Broadcom, Inc.'
