sources:
- archive: photon-os-installer-2.7.tar.gz
  archive_sha512sum: f73110ea9bb3154759fe2de091eb25e0963903ed469f952097d48c12a4dc10a11edf7a08bf3e506de7a14b40919cee1c135d36626485db392f9b0a74f0a95129
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Installer to build Photon images '
      home_page: https://github.com/vmware/photon-os-installer
      license_concluded: Apache-2.0 AND (Apache-2.0 OR GPL-2.0-only) AND GPL-2.0-only
      license_declared: Apache-2.0 AND (Apache-2.0 OR GPL-2.0-only) AND GPL-2.0-only
      short_summary: Photon OS Installer
      supplier: 'Organization: Broadcom, Inc.'
