sources:
- archive: photon-os-installer-2.7.tar.gz
  archive_sha512sum: 012015d42fb80ec30a421550e676b7bc8ba9c647257bae0190e7f0386a1e49358b38b67dbe0bb913d30102146fc72e74d082d05c99f75a303aec3f59630dddd3
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Installer to build Photon images '
      home_page: https://github.com/vmware/photon-os-installer
      license_concluded: Apache-2.0 AND (Apache-2.0 OR GPL-2.0-only) AND GPL-2.0-only
      license_declared: Apache-2.0 AND (Apache-2.0 OR GPL-2.0-only) AND GPL-2.0-only
      short_summary: Photon OS Installer
      supplier: 'Organization: Broadcom, Inc.'
