sources:
- archive: node-v22.16.0.tar.gz
  archive_sha512sum: 50a41c315f86a682e9f67c8259d4e1180571ea1d66efe8454662acaa1a5f6ee2297f88ca3dc4b7a6a76885739e0c5de25a1b13ccb4e39e987ae6b3b3f03152ab
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Node.js is a JavaScript runtime built on Chrome''s V8
        JavaScript engine. Node.js uses an event-driven, non-blocking I/O model that
        makes it lightweight and efficient. The Node.js package ecosystem, npm, is
        the largest ecosystem of open source libraries in the world. '
      home_page: https://github.com/nodejs/node
      license_concluded: (MIT OR Apache-2.0) AND (BSD-2-Clause OR Apache-2.0) AND
        (GPL-2.0-only OR BSD-3-Clause) AND (OpenSSL OR BSD-3-Clause OR GPL-1.0-or-later)
        AND (OpenSSL OR BSD-2-Clause) AND (GPL-1.0-or-later OR Artistic-1.0) AND (BSD-3-Clause
        OR Apache-2.0) AND (Artistic-1.0-Perl OR GPL-1.0-or-later) AND (MIT OR GPL-1.0-or-later)
        AND (CC0-1.0 OR BSD-2-Clause) AND (GPL-2.0-or-later OR LGPL-2.1-or-later OR
        MPL-1.1 OR BSD-3-Clause) AND (ISC OR MIT) AND (BSD-3-Clause OR GPL-2.0-only)
        AND (GPL-1.0-or-later OR Artistic-1.0-Perl) AND (OpenSSL OR BSD-3-Clause)
        AND (OpenSSL OR BSD-3-Clause OR GPL-1.0-or-later OR GPL-2.0-only) AND X11
        AND EPL-1.0 AND PolyForm-Small-Business-1.0.0 AND IBM-pibs AND BSD-3-Clause-Clear
        AND BSL-1.0 AND FSFULLRWD AND APSL-1.0 AND LAL-1.3 AND GPL-2.0-or-later WITH
        Autoconf-exception-generic AND GFDL-1.2-invariants-only AND GFDL-1.2-no-invariants-only
        AND OGL-UK-3.0 AND OGC-1.0 AND GPL-1.0-or-later AND GFDL-1.3-no-invariants-or-later
        AND CC-BY-SA-2.0 AND CAL-1.0 AND copyleft-next-0.3.1 AND NIST-PD-fallback
        AND Frameworx-1.0 AND AFL-3.0 AND CERN-OHL-S-2.0 AND BSD-3-Clause AND CDDL-1.1
        AND Apache-1.1 AND GFDL-1.1-only AND GFDL-1.1-invariants-or-later AND TMate
        AND SunPro AND CECILL-2.0 AND GPL-2.0-or-later WITH Libtool-exception AND
        MPL-1.0 AND CDDL-1.0 AND BSD-3-Clause-Modification AND snprintf AND CC-BY-SA-4.0
        AND CERN-OHL-1.1 AND OGL-Canada-2.0 AND GPL-2.0-or-later WITH Autoconf-exception-2.0
        AND SSPL-1.0 AND Zimbra-1.4 AND GFDL-1.2-invariants-or-later AND NCGL-UK-2.0
        AND CECILL-2.1 AND WTFPL AND AGPL-3.0-only AND copyleft-next-0.3.0 AND CC0-1.0
        AND Python-2.0 AND Zimbra-1.3 AND HPND-sell-variant AND LGPL-3.0-only AND
        Spencer-86 AND CAL-1.0-Combined-Work-Exception AND libselinux-1.0 AND GPL-3.0-or-later
        WITH Autoconf-exception-2.0 AND EFL-2.0 AND BlueOak-1.0.0 AND etalab-2.0 AND
        ISC AND Artistic-2.0 AND NIST-PD AND Parity-7.0.0 AND BSD-Source-Code AND
        BSD-2-Clause-Patent AND OGL-UK-1.0 AND CC-BY-4.0 AND LGPL-2.1-or-later AND
        NAIST-2003 AND Unicode-3.0 AND APSL-2.0 AND BSD-4-Clause-Shortened AND PSF-2.0
        AND BSD-2-Clause-Views AND MIT-0 AND HaskellReport AND LGPL-2.0-or-later AND
        TU-Berlin-2.0 AND NGPL AND OFL-1.1-no-RFN AND JSON AND BSD-2-Clause AND TU-Berlin-1.0
        AND LiLiQ-R-1.1 AND GFDL-1.2-no-invariants-or-later AND LiLiQ-P-1.1 AND AGPL-1.0-only
        AND GPL-1.0-only AND NTP AND OpenSSL AND bzip2-1.0.6 AND HPND AND CC-BY-3.0
        AND blessing AND GPL-2.0-or-later AND Linux-man-pages-copyleft AND TAPR-OHL-1.0
        AND MPL-2.0 AND GPL-3.0-or-later AND LiLiQ-Rplus-1.1 AND GFDL-1.3-invariants-only
        AND Parity-6.0.0 AND ICU AND CERN-OHL-1.2 AND GFDL-1.1-no-invariants-only
        AND NTP-0 AND LGPL-3.0-or-later AND MIT-Wu AND BSD-3-Clause-No-Military-License
        AND GPL-2.0-or-later WITH eCos-exception-2.0 AND Zlib AND BSD-4-Clause-UC
        AND APSL-1.1 AND GPL-3.0-only AND GFDL-1.1-invariants-only AND LGPL-2.1-only
        AND GFDL-1.3-invariants-or-later AND curl AND MIT AND Artistic-1.0 AND AGPL-3.0-or-later
        AND CERN-OHL-W-2.0 AND CPOL-1.02 AND FSFUL AND CERN-OHL-P-2.0 AND GPL-2.0-only
        AND Apache-2.0 WITH LLVM-exception AND FSFAP AND Interbase-1.0 AND Apache-2.0
        AND BSD-4-Clause AND FSFULLR AND UCL-1.0 AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0
        AND GFDL-1.1-no-invariants-or-later AND PolyForm-Noncommercial-1.0.0 AND OGL-UK-2.0
        AND OGDL-Taiwan-1.0 AND GFDL-1.3-no-invariants-only
      license_declared: (MIT OR Apache-2.0) AND (BSD-2-Clause OR Apache-2.0) AND (GPL-2.0-only
        OR BSD-3-Clause) AND (OpenSSL OR BSD-3-Clause OR GPL-1.0-or-later) AND (OpenSSL
        OR BSD-2-Clause) AND (GPL-1.0-or-later OR Artistic-1.0) AND (BSD-3-Clause
        OR Apache-2.0) AND (Artistic-1.0-Perl OR GPL-1.0-or-later) AND (MIT OR GPL-1.0-or-later)
        AND (CC0-1.0 OR BSD-2-Clause) AND (GPL-2.0-or-later OR LGPL-2.1-or-later OR
        MPL-1.1 OR BSD-3-Clause) AND (ISC OR MIT) AND (BSD-3-Clause OR GPL-2.0-only)
        AND (GPL-1.0-or-later OR Artistic-1.0-Perl) AND (OpenSSL OR BSD-3-Clause)
        AND (OpenSSL OR BSD-3-Clause OR GPL-1.0-or-later OR GPL-2.0-only) AND X11
        AND EPL-1.0 AND PolyForm-Small-Business-1.0.0 AND IBM-pibs AND BSD-3-Clause-Clear
        AND BSL-1.0 AND FSFULLRWD AND APSL-1.0 AND LAL-1.3 AND GPL-2.0-or-later WITH
        Autoconf-exception-generic AND GFDL-1.2-invariants-only AND GFDL-1.2-no-invariants-only
        AND OGL-UK-3.0 AND OGC-1.0 AND GPL-1.0-or-later AND GFDL-1.3-no-invariants-or-later
        AND CC-BY-SA-2.0 AND CAL-1.0 AND copyleft-next-0.3.1 AND NIST-PD-fallback
        AND Frameworx-1.0 AND AFL-3.0 AND CERN-OHL-S-2.0 AND BSD-3-Clause AND CDDL-1.1
        AND Apache-1.1 AND GFDL-1.1-only AND GFDL-1.1-invariants-or-later AND TMate
        AND SunPro AND CECILL-2.0 AND GPL-2.0-or-later WITH Libtool-exception AND
        MPL-1.0 AND CDDL-1.0 AND BSD-3-Clause-Modification AND snprintf AND CC-BY-SA-4.0
        AND CERN-OHL-1.1 AND OGL-Canada-2.0 AND GPL-2.0-or-later WITH Autoconf-exception-2.0
        AND SSPL-1.0 AND Zimbra-1.4 AND GFDL-1.2-invariants-or-later AND NCGL-UK-2.0
        AND CECILL-2.1 AND WTFPL AND AGPL-3.0-only AND copyleft-next-0.3.0 AND CC0-1.0
        AND Python-2.0 AND Zimbra-1.3 AND HPND-sell-variant AND LGPL-3.0-only AND
        Spencer-86 AND CAL-1.0-Combined-Work-Exception AND libselinux-1.0 AND GPL-3.0-or-later
        WITH Autoconf-exception-2.0 AND EFL-2.0 AND BlueOak-1.0.0 AND etalab-2.0 AND
        ISC AND Artistic-2.0 AND NIST-PD AND Parity-7.0.0 AND BSD-Source-Code AND
        BSD-2-Clause-Patent AND OGL-UK-1.0 AND CC-BY-4.0 AND LGPL-2.1-or-later AND
        NAIST-2003 AND Unicode-3.0 AND APSL-2.0 AND BSD-4-Clause-Shortened AND PSF-2.0
        AND BSD-2-Clause-Views AND MIT-0 AND HaskellReport AND LGPL-2.0-or-later AND
        TU-Berlin-2.0 AND NGPL AND OFL-1.1-no-RFN AND JSON AND BSD-2-Clause AND TU-Berlin-1.0
        AND LiLiQ-R-1.1 AND GFDL-1.2-no-invariants-or-later AND LiLiQ-P-1.1 AND AGPL-1.0-only
        AND GPL-1.0-only AND NTP AND OpenSSL AND bzip2-1.0.6 AND HPND AND CC-BY-3.0
        AND blessing AND GPL-2.0-or-later AND Linux-man-pages-copyleft AND TAPR-OHL-1.0
        AND MPL-2.0 AND GPL-3.0-or-later AND LiLiQ-Rplus-1.1 AND GFDL-1.3-invariants-only
        AND Parity-6.0.0 AND ICU AND CERN-OHL-1.2 AND GFDL-1.1-no-invariants-only
        AND NTP-0 AND LGPL-3.0-or-later AND MIT-Wu AND BSD-3-Clause-No-Military-License
        AND GPL-2.0-or-later WITH eCos-exception-2.0 AND Zlib AND BSD-4-Clause-UC
        AND APSL-1.1 AND GPL-3.0-only AND GFDL-1.1-invariants-only AND LGPL-2.1-only
        AND GFDL-1.3-invariants-or-later AND curl AND MIT AND Artistic-1.0 AND AGPL-3.0-or-later
        AND CERN-OHL-W-2.0 AND CPOL-1.02 AND FSFUL AND CERN-OHL-P-2.0 AND GPL-2.0-only
        AND Apache-2.0 WITH LLVM-exception AND FSFAP AND Interbase-1.0 AND Apache-2.0
        AND BSD-4-Clause AND FSFULLR AND UCL-1.0 AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0
        AND GFDL-1.1-no-invariants-or-later AND PolyForm-Noncommercial-1.0.0 AND OGL-UK-2.0
        AND OGDL-Taiwan-1.0 AND GFDL-1.3-no-invariants-only
      short_summary: A JavaScript runtime built on Chrome's V8 JavaScript engine.
      supplier: 'Organization: Broadcom, Inc.'
