sources:
- archive: go1.23.10.src.tar.gz
  archive_sha512sum: 20639185b05720aa8bb295c54e3eaa7cf56739763544d28ce14a6f0323bf890900d5fad13086032291fbefad4482f1442772875bbdf16a94e2286eb405c8f327
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Go is an open source programming language that makes
        it easy to build simple, reliable, and efficient software. '
      home_page: https://golang.org
      license_concluded: IJG AND OpenSSL-standalone AND MIT-testregex AND BSD-1-Clause
        AND GPL-2.0-only AND SSLeay-standalone AND MIT AND BSD-3-Clause AND Apache-2.0
        AND ISC AND BSD-2-Clause AND GPL-1.0-or-later AND MPEG-SSG AND SunPro AND
        CC-BY-4.0
      license_declared: IJG AND OpenSSL-standalone AND MIT-testregex AND BSD-1-Clause
        AND GPL-2.0-only AND SSLeay-standalone AND MIT AND BSD-3-Clause AND Apache-2.0
        AND ISC AND BSD-2-Clause AND GPL-1.0-or-later AND MPEG-SSG AND SunPro AND
        CC-BY-4.0
      short_summary: Go
      supplier: 'Organization: Broadcom, Inc.'
