sources:
- archive: containerd-2.1.1.tar.gz
  archive_type: upstream
  version: 2.1.1
  name: containerd-2.1.1
  url: https://github.com/containerd/containerd/archive/refs/tags/v2.1.1.tar.gz
  repo_url: https://github.com/containerd/containerd.git
  commit_id: cb1076646aa3740577fafbf3d914198b7fe8e3f7
  skip_list: []
  missing: []
  archive_sha512sum: 542f7cae61e1ef2e1b529b0bea66d7ad9016d4605de73de9c9c8a738e50ec6f470b939d1546482320515b77424bffe1cf24b721173ac0c0ecd0100c92817cfb1
  skip_validation: false
  spdx:
    package:
      detailed_description: 'Containerd is an open source project. It is available
        as a daemon for Linux, which manages the complete container lifecycle of its
        host system. '
      home_page: https://containerd.io/docs
      license_concluded: MIT AND GPL-1.0-or-later AND BSD-2-Clause AND CC-BY-SA-4.0
        AND MPL-2.0 AND Apache-2.0 AND ISC AND BSD-3-Clause
      license_declared: MIT AND GPL-1.0-or-later AND BSD-2-Clause AND CC-BY-SA-4.0
        AND MPL-2.0 AND Apache-2.0 AND ISC AND BSD-3-Clause
      short_summary: Containerd
      supplier: 'Organization: Broadcom, Inc.'
