sources:
- archive: pgbouncer-1.26.0.tar.gz
  archive_sha512sum: ada8440759e51f1a8690b700a64e21ee2929f3ef60a204ac93681bf85369c79380c44375e9261826d5d37e3d789379c505532ac27bc4ab997c56b75974ab0718
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Pgbouncer is a light-weight, robust connection pooler
        for PostgreSQL. '
      home_page: https://wiki.postgresql.org/wiki/PgBouncer
      license_concluded: ISC AND GPL-3.0-or-later WITH Autoconf-exception-2.0 AND
        CC0-1.0 AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND X11 AND
        FSFUL AND BSD-2-Clause AND BSD-3-Clause
      license_declared: ISC AND GPL-3.0-or-later WITH Autoconf-exception-2.0 AND CC0-1.0
        AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND X11 AND FSFUL
        AND BSD-2-Clause AND BSD-3-Clause
      short_summary: Connection pooler for PostgreSQL.
      supplier: 'Organization: Broadcom, Inc.'
