sources:
- archive: Module-Install-1.21.tar.gz
  archive_sha512sum: f3dd1dfcae81704f1aa9ac409abd22c9e0d5d66c048adac13da19ab88559d717427b5471b7a065db8312d4d44e829afea52567cd0993e4016df0e10c760ada85
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Module::Install is a package for writing installers for
        CPAN (or CPAN-like) distributions that are clean, simple, minimalist, act
        in a strictly correct manner with ExtUtils::MakeMaker, and will run on any
        Perl installation version 5.005 or newer. '
      home_page: http://search.cpan.org/dist/Module-Install/
      license_concluded: (GPL-1.0-or-later OR Artistic-1.0-Perl) AND (Artistic-1.0-Perl
        OR GPL-1.0-or-later) AND LGPL-2.0-only AND GPL-3.0-only AND LGPL-2.1-only
        AND GFDL-1.1-or-later AND GPL-1.0-or-later AND Artistic-2.0 AND LGPL-2.0-or-later
        AND BSD-3-Clause AND AGPL-3.0-or-later AND Artistic-1.0-Perl AND MIT AND GPL-1.0-only
        AND Apache-1.1 AND OpenSSL AND MPL-1.0 AND Zlib AND Apache-2.0 AND LGPL-2.1-or-later
        AND LGPL-3.0-only AND GPL-2.0-only AND MPL-1.1
      license_declared: (GPL-1.0-or-later OR Artistic-1.0-Perl) AND (Artistic-1.0-Perl
        OR GPL-1.0-or-later) AND LGPL-2.0-only AND GPL-3.0-only AND LGPL-2.1-only
        AND GFDL-1.1-or-later AND GPL-1.0-or-later AND Artistic-2.0 AND LGPL-2.0-or-later
        AND BSD-3-Clause AND AGPL-3.0-or-later AND Artistic-1.0-Perl AND MIT AND GPL-1.0-only
        AND Apache-1.1 AND OpenSSL AND MPL-1.0 AND Zlib AND Apache-2.0 AND LGPL-2.1-or-later
        AND LGPL-3.0-only AND GPL-2.0-only AND MPL-1.1
      short_summary: Standalone, extensible Perl module installer
      supplier: 'Organization: Broadcom, Inc.'
