sources:
- archive: cargo-1.86.0-x86_64-unknown-linux-gnu.tar.xz
  archive_sha512sum: 19ef3de97fc0a21bde800c5a10bfda835d9cc48399d473b65e245d2b16d42e172454579eca4c4acd72107e0a5796d82ea185b834a2d9a23cf27e74c02232bc3e
  skip_validation: true
  spdx:
    package:
      detailed_description: cargo bootstrap toolchain to build rust-lang
      home_page: https://static.rust-lang.org
      license_concluded: (Apache-2.0 OR MIT) AND GPL-2.0-only AND OpenSSL-standalone
        AND LGPL-2.1-only AND Apache-2.0 AND Zlib AND SSLeay-standalone AND LGPL-2.0-or-later
        AND curl AND (MIT OR Apache-2.0) AND BSD-3-Clause AND MIT AND Unlicense AND
        GPL-2.0-only WITH GCC-exception-2.0
      license_declared: (Apache-2.0 OR MIT) AND GPL-2.0-only AND OpenSSL-standalone
        AND LGPL-2.1-only AND Apache-2.0 AND Zlib AND SSLeay-standalone AND LGPL-2.0-or-later
        AND curl AND (MIT OR Apache-2.0) AND BSD-3-Clause AND MIT AND Unlicense AND
        GPL-2.0-only WITH GCC-exception-2.0
      short_summary: cargo bootstrap toolchain to build rust-lang
      supplier: 'Organization: Broadcom, Inc.'
- archive: rust-std-1.86.0-x86_64-unknown-linux-gnu.tar.xz
  archive_sha512sum: 4e6c73db6eb9235d0656eaa04d968d7e0ee0b1beb132e59affcfcb9141e3da0861fdf900109c66221a20bc70d4150f19955419ff865b34aa5b883d7b4fc0ab0b
  skip_validation: true
  spdx:
    package:
      detailed_description: std toolchain requried to build rust-lang
      home_page: https://static.rust-lang.org
      license_concluded: (Apache-2.0 OR MIT) AND NCSA AND (MIT OR Apache-2.0) AND
        Unicode-3.0 AND MIT AND Apache-2.0 AND BSD-2-Clause AND Apache-2.0 WITH LLVM-exception
      license_declared: (Apache-2.0 OR MIT) AND NCSA AND (MIT OR Apache-2.0) AND Unicode-3.0
        AND MIT AND Apache-2.0 AND BSD-2-Clause AND Apache-2.0 WITH LLVM-exception
      short_summary: std toolchain requried to build rust-lang
      supplier: 'Organization: Broadcom, Inc.'
- archive: rustc-1.86.0-x86_64-unknown-linux-gnu.tar.xz
  archive_sha512sum: 849d324b79918a1796288425b5121e6ca1d55a7588dfa1d284c07c2f6c39ee94775b4e74dbd7e99cf9b471b3744d403310455b33e898378d09ecad853d1f0c88
  skip_validation: true
  spdx:
    package:
      detailed_description: Bootstrap toolchain requried to build rust-lang
      home_page: https://static.rust-lang.org
      license_concluded: NCSA AND Apache-2.0 AND MIT AND Apache-2.0 WITH LLVM-exception
        AND (Apache-2.0 OR MIT) AND OFL-1.1 AND BSD-2-Clause AND Unicode-3.0 AND (MIT
        OR Apache-2.0)
      license_declared: NCSA AND Apache-2.0 AND MIT AND Apache-2.0 WITH LLVM-exception
        AND (Apache-2.0 OR MIT) AND OFL-1.1 AND BSD-2-Clause AND Unicode-3.0 AND (MIT
        OR Apache-2.0)
      short_summary: Bootstrap toolchain requried to build rust-lang
      supplier: 'Organization: Broadcom, Inc.'
- archive: rustc-1.87.0-src.tar.xz
  archive_sha512sum: 2ef08c9be45434401f916d54b3739f52d255f8a3a4ce05a717499250c2333eeaf601f1d18085b878c027c609f44da74d0151f5bfc2c9ae1e01166919a91a1d2b
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Rust Programming Language '
      home_page: https://github.com/rust-lang/rust
      license_concluded: GPL-2.0-or-later AND (MIT OR Apache-2.0) AND BSD-4-Clause-UC
        AND (NCSA OR MIT) AND CC-BY-SA-4.0 AND GPL-2.0-or-later WITH GNAT-exception
        AND FSFULLR AND FSFULLRWD AND (Apache-2.0 OR MIT) AND GPL-3.0-or-later WITH
        Autoconf-exception-2.0 AND CC-BY-NC-SA-4.0 AND GPL-2.0-only AND GPL-3.0-only
        AND (curl AND ISC) AND HPND-UC AND snprintf AND BSD-1-Clause AND MIT-0 AND
        CC-PDDC AND curl AND CC-BY-3.0 AND (GPL-2.0-only OR MIT) AND Apache-2.0 AND
        BlueOak-1.0.0 AND Beerware AND Spencer-94 AND (MIT OR Apache-2.0 OR BSD-1-Clause)
        AND GPL-3.0-or-later WITH Autoconf-exception-macro AND (MIT OR GPL-2.0-only)
        AND FSFAP AND FSFUL AND Nokia AND NCSA AND Apache-2.0 WITH LLVM-exception
        AND (MIT OR Unlicense) AND FSFAP-no-warranty-disclaimer AND OFL-1.1 AND (GPL-2.0-or-later
        OR MIT) AND (MIT OR CC0-1.0) AND SunPro AND ICU AND GPL-2.0-only WITH GCC-exception-2.0
        AND Unlicense AND GPL-3.0-or-later AND (MIT OR GPL-1.0-or-later) AND Artistic-1.0-Perl
        AND OpenSSL-standalone AND BSL-1.0 AND Artistic-2.0 AND (Apache-2.0 OR MIT)
        AND GPL-1.0-or-later WITH Autoconf-exception-generic AND 0BSD AND APSL-2.0
        AND LGPL-2.1-or-later AND LGPL-2.1-only AND CC-BY-SA-3.0 AND GPL-3.0-or-later
        WITH Texinfo-exception AND MPL-2.0 AND Zlib AND X11 AND GPL-3.0-or-later WITH
        Autoconf-exception-generic-3.0 AND GPL-2.0-or-later WITH Autoconf-exception-generic
        AND MIT AND BSD-Source-Code AND CC-BY-4.0 AND ISC AND OpenSSL AND GFDL-1.1-or-later
        AND MIT-testregex AND JSON AND LPD-document AND CC0-1.0 AND GPL-1.0-or-later
        AND BSD-2-Clause-Views AND BSD-2-Clause AND BSD-3-Clause AND GPL-2.0-or-later
        WITH Libtool-exception AND (NCSA OR MIT) AND SSH-short AND SSLeay-standalone
        AND W3C AND Apache-1.0 AND Unicode-DFS-2016 AND (Apache-2.0 WITH LLVM-exception
        OR Apache-2.0 OR MIT) AND LGPL-2.0-or-later AND (GPL-2.0-or-later OR LGPL-2.1-or-later
        OR MPL-1.1 OR BSD-3-Clause) AND Python-2.0 AND (MIT OR Apache-2.0)
      license_declared: GPL-2.0-or-later AND (MIT OR Apache-2.0) AND BSD-4-Clause-UC
        AND (NCSA OR MIT) AND CC-BY-SA-4.0 AND GPL-2.0-or-later WITH GNAT-exception
        AND FSFULLR AND FSFULLRWD AND (Apache-2.0 OR MIT) AND GPL-3.0-or-later WITH
        Autoconf-exception-2.0 AND CC-BY-NC-SA-4.0 AND GPL-2.0-only AND GPL-3.0-only
        AND (curl AND ISC) AND HPND-UC AND snprintf AND BSD-1-Clause AND MIT-0 AND
        CC-PDDC AND curl AND CC-BY-3.0 AND (GPL-2.0-only OR MIT) AND Apache-2.0 AND
        BlueOak-1.0.0 AND Beerware AND Spencer-94 AND (MIT OR Apache-2.0 OR BSD-1-Clause)
        AND GPL-3.0-or-later WITH Autoconf-exception-macro AND (MIT OR GPL-2.0-only)
        AND FSFAP AND FSFUL AND Nokia AND NCSA AND Apache-2.0 WITH LLVM-exception
        AND (MIT OR Unlicense) AND FSFAP-no-warranty-disclaimer AND OFL-1.1 AND (GPL-2.0-or-later
        OR MIT) AND (MIT OR CC0-1.0) AND SunPro AND ICU AND GPL-2.0-only WITH GCC-exception-2.0
        AND Unlicense AND GPL-3.0-or-later AND (MIT OR GPL-1.0-or-later) AND Artistic-1.0-Perl
        AND OpenSSL-standalone AND BSL-1.0 AND Artistic-2.0 AND (Apache-2.0 OR MIT)
        AND GPL-1.0-or-later WITH Autoconf-exception-generic AND 0BSD AND APSL-2.0
        AND LGPL-2.1-or-later AND LGPL-2.1-only AND CC-BY-SA-3.0 AND GPL-3.0-or-later
        WITH Texinfo-exception AND MPL-2.0 AND Zlib AND X11 AND GPL-3.0-or-later WITH
        Autoconf-exception-generic-3.0 AND GPL-2.0-or-later WITH Autoconf-exception-generic
        AND MIT AND BSD-Source-Code AND CC-BY-4.0 AND ISC AND OpenSSL AND GFDL-1.1-or-later
        AND MIT-testregex AND JSON AND LPD-document AND CC0-1.0 AND GPL-1.0-or-later
        AND BSD-2-Clause-Views AND BSD-2-Clause AND BSD-3-Clause AND GPL-2.0-or-later
        WITH Libtool-exception AND (NCSA OR MIT) AND SSH-short AND SSLeay-standalone
        AND W3C AND Apache-1.0 AND Unicode-DFS-2016 AND (Apache-2.0 WITH LLVM-exception
        OR Apache-2.0 OR MIT) AND LGPL-2.0-or-later AND (GPL-2.0-or-later OR LGPL-2.1-or-later
        OR MPL-1.1 OR BSD-3-Clause) AND Python-2.0 AND (MIT OR Apache-2.0)
      short_summary: Rust Programming Language
      supplier: 'Organization: Broadcom, Inc.'
